Acarusillo
TUSI-UTN/TP1_GRUPO_X pull request #2
Opened 2023-03-27 20:01 UTC by CarusilloAgustin

Nueva clase "Genre" creada.
ToString en la clase ticket agregado
ToString en la clase ChildrensEventTicket agregado
Se progresó con la clase ChildrensEventTicket

2023-03-27 20:21 UTC, tomsct requested changes

2023-03-27 20:21 UTC, tomsct commented on src/entities/ChildrensEventTicket.java
> +		if(this.age < 8) {
Aca lo mismo preguntaria como en la clase RecitalTicket si es MAYOR o MENOR

2023-03-27 20:21 UTC, tomsct commented on src/entities/ChildrensEventTicket.java
> +	 private int age;
no seria necesario en  principio si usamos el approach de la interfaz

2023-03-27 20:21 UTC, tomsct commented on src/entities/ChildrensEventTicket.java
> +	public int getAge() {
no seria necesario si usamos la interfaz

2023-03-27 20:21 UTC, tomsct commented on src/entities/Ticket.java
> +	    return "N�mero de entrada: " + getId() + "\nNombre del show: " + getName() + "\nFecha y hora del evento: " + getDateTime() + "\nDuraci�n aproximada: " + getMinutes() + " minutos\n";
esto no iria ya que se implementaria en cada clase hija

2023-03-27 20:59 UTC, CarusilloAgustin commented on src/entities/Ticket.java
> -	public abstract String toString();
Mi idea era que herede del padre el metodo con los campos que comparten todas las entradas y despues concatenamos a ese string solo los campos caracteristicos de cada clase

2023-03-28 04:04 UTC, tomsct commented
Me parece bien aprobarlo en principio, despues si hay que hacerle algun cambio lo vamos viendo. Que piensan? @BrianFranco @mledesma3 @PabloATorres91

2023-03-29 00:53 UTC, tomsct approved these changes

2023-03-29 00:53 UTC, merged